# Generated by Django 4.2 on 2024-06-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_estudiante_cedula_alter_profesor_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='detallenota',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detallenota',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
