# Generated by Django 4.2 on 2024-06-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_update_asignatura_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]
